[build]
  functions = "netlify/functions"
  NODE_ENV = "production"
  NETLIFY_BLOBS_CONTEXT = "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  port = 8888

[functions."co2data"]
  included_files = ["node_modules/**"]
